### PR TITLE
Revise console output API.

### PR DESCRIPTION
**Pull request by merijn**
Make it easier to access the name of a test/group for things like labelling.

Add a way to report statistics without timing.

Updated @since annotations to reflect the current type and updated the version in accordance with PVP.

### CODE REVIEW

**Comment by feuerbach** [comment]
It's a shame that we need to bump the major version — it'll affect a lot of people without a good reason. But I guess that's the price of the PVP.

Could you squash the two commits together and force-push? Also, could you add a changelog entry?

**Comment by merijn** [comment]
Yeah, it's a shame I didn't realise I needed this before pushing the initial version. I doubt anyone but me has actually started using this code since it was released, so not bumping the major version is *probably* fine, but I decided to err on the side of caution.

**Comment by merijn** [comment]
Ok, pushed a squashed version.

**Comment by feuerbach** [comment]
Cool, could you also add a changelog entry?

**Comment by merijn** [comment]
Apparently I can't "git" well, so this got closed when I was trying to revise it to include the CHANGELOG. The fixed version is in #188

**Pull request closed without merging**
