### PR TITLE
Update continuous integration with Travis

### PR DESCRIPTION
**Pull request by sjakobi**
- Use Travis' (supposedly quicker) container-based infrastructure
- Add GHC-7.10.2 and GHC-head to the build matrix
- Cache the .cabal and .ghc directories

### CODE REVIEW

**Comment by feuerbach** [comment]
By preserving .ghc, aren't we risking to run into cabal hell?

**Comment by sjakobi** [comment]
> By preserving .ghc, aren't we risking to run into cabal hell?

It doesn't seem to be much of problem in practice, the stack project currently does [the same](https://github.com/commercialhaskell/stack/blob/master/.travis.yml).
If it should turn out to be a problem, the cache can manually be [cleared](http://docs.travis-ci.com/user/caching/#Clearing-Caches).

The caching isn't necessary of course. I can simply leave that out if you prefer.

**Comment by feuerbach** [comment]
I think it's better to leave it out. Another potential problem is that instead of building with latest versions of dependencies, it will build with some arbitrary fixed versions (which are cached).

**Comment by chreekat** [comment]
I'm just passing by, but I noticed that commits were added to this PR. I know that doesn't cause an update, so, "ping".

**Comment by feuerbach** [comment]
I know about this PR. Still need to test and review it. It would also be nice to update all my travis.yamls to be similar/identical.

**Comment by neongreen** [comment]
> it will build with some arbitrary fixed versions (which are cached)

This is a concern, yes. Perhaps you could use a travis.yml file generated by hvr's [multi-ghc-travis](https://github.com/hvr/multi-ghc-travis) script? It does caching too but it's more clever about it – it only uses the cache if the build-plan for the package doesn't differ from the build-plan stored with the cache, which is supposed to prevent the problem of stale dependencies.

**Comment by feuerbach** [comment]
.travis.yml is now updated, thanks.

**Pull request closed without merging**
