### PR TITLE
Mention tasty-jenkins-xml in README

### PR DESCRIPTION
**Pull request by liskin**
Shameless plug. :-)

### CODE REVIEW

**Comment by feuerbach** [comment]
Thanks. Have you seen this discussion? Would it solve your problem? https://github.com/feuerbach/tasty/issues/158

**Comment by liskin** [comment]
Oh, no, I haven't. I wrote the code a few days before that. :-(

**Comment by liskin** [comment]
Anyway, I had a quick look and it looks way simpler than my solution. The only thing that it can't do is the `--exit-success` thing (which exits successfully if the test finished and the result is correctly written to file and then relies on jenkins' junit plugin to mark the build as unstable).

**Comment by feuerbach** [comment]
Hmm, I don't follow. Could you explain in a bit more detail that scenario?

**Comment by liskin** [comment]
We want to distinguish between build/execution failures and just failed tests. Jenkins supports this by having different job results: FAILED and UNSTABLE. When a build script exits with a non-zero exit code, jenkins marks the build as failed. When it exits with zero and outputs a few JUnit XMLs, the JUnit Plugin can then mark the build as unstable if there are any failed tests. So we need a way to exit successfully even if some tests failed. But now that I think about it, maybe we should just catch the ExitCode exception. Why haven't I thought about all this before? :-)

**Comment by feuerbach** [comment]
I see, thanks for explaining. Could you get in touch with the maintainers of tasty-ant-xml and see if they are willing to incorporate the remaining functionality in that package?

**Comment by liskin** [comment]
I think I can. :-)

**Pull request closed without merging**
