### PR TITLE
Refactoring for #196

### PR DESCRIPTION
**Pull request by asr**
From our previous discussion in https://github.com/feuerbach/tasty/issues/196#issuecomment-353880917, we know that `mappend` is defined as `(<>)` by default. In this PR I used this fact for refactoring the fix of #196.

### CODE REVIEW

**Comment by feuerbach** [comment]
What's the purpose of this? It looks like it complicates things for no reason.

**Comment by quasicomputational** [comment]
Soon GHC will be warning about non-canonical `Monoid` definitions (where the canonical definition is `mappend = (<>)`). There's a long-term idea of removing `mappend` from `Monoid` altogether and leaving it as an alias for `(<>)`, but I don't know if that's going to realistically happen. The general idea is that `mappend` and `(<>)` should be identical, and, since `Semigroup` is a superclass of `Monoid`, it makes the most sense to define `(<>)` explicitly.

This changeset is probably over-complicated: I'd drop the CPP and add a dependency on the semigroups package (which is already transitively pulled in through optparse-applicative), and then define `(<>)` as the source of truth and leave in `mappend = (<>)` for compatibility.

**Comment by asr** [comment]
> This changeset is probably over-complicated: I'd drop the CPP and add a dependency on the semigroups package (which is already transitively pulled in through optparse-applicative), and then define `(<>)` as the source of truth and leave in `mappend = (<>)` for compatibility.

I agree. On fact, this is what I made in #197 (but you rejected it due to the dependency on semigroups).

**Comment by asr** [comment]
> Soon GHC will be warning about non-canonical Monoid definitions (where the canonical definition is `mappend = (<>)`).

Note that this PR uses the canonical Monoid definition.

**Comment by feuerbach** [comment]
> which is already transitively pulled in through optparse-applicative

This is a good point I haven't considered before, and when this becomes an issue, I'll do as you say. But for now, I honestly don't see why we are wasting each other's time having this discussion.

So I'll repeat the question: does this PR solve any problem right now?

**Comment by asr** [comment]
> So I'll repeat the question: does this PR solve any problem right now?

No. I thought that the fix of #196 using something like

```
instance Semigroup Foo where
  (<>) = mappend
#endif
```
wasn't the best. This PR was my attempt of a better fix. Since you are thinking of including a dependency in the semigroup package, this PR is "outdated".

**Pull request closed without merging**
